import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.location().url.includes('/api/listings'))errors.push(m.text())});
await page.goto('http://localhost:5173/?layer=age&year=2026');await page.waitForFunction(()=>window.__atlas,null,{timeout:90000});await page.waitForFunction(()=>document.querySelectorAll('.map-label:not([hidden])').length>3);
// Cesium applies data styles when tiles become visible. Panning the expanded
// model leaves cached offscreen tiles in loadedContents; inspect rendered tiles.
await page.evaluate(()=>{window.__visibleContents=new Map();__atlas.viewer.scene.preUpdate.addEventListener(()=>__visibleContents.clear());__atlas.tileset.tileVisible.addEventListener(tile=>{if(tile.content?.featuresLength)__visibleContents.set(tile.content.url,tile.content);});});
const state=()=>page.evaluate(()=>({...__atlas.nav.state})),settled=()=>page.waitForFunction(()=>!__atlas.nav.flight);
console.log('Initial',await page.evaluate(()=>({buildings:__atlas.manifest.length,tiles:__atlas.loadedContents.size,labels:document.querySelectorAll('.map-label:not([hidden])').length})));
await page.screenshot({path:'artifacts/atlas-desktop.png'});
const before=await state();await page.mouse.move(750,500);await page.mouse.down();await page.mouse.move(980,545,{steps:20});await page.mouse.up();const dragged=await state();assert.ok(Math.abs(dragged.lon-before.lon)>.0001,'drag must pan');
await page.mouse.wheel(0,-300);await page.waitForFunction(r=>__atlas.nav.state.range<r,dragged.range);const wheeled=await state();await page.locator('#zoom-in').click();assert.ok((await state()).range<wheeled.range);await page.locator('#zoom-out').click();
await page.locator('#perspective').click();assert.equal((await state()).pitch,-88);await page.locator('#perspective').click();assert.equal((await state()).pitch,-48);await page.locator('#rotate-right').click();assert.notEqual((await state()).heading,before.heading);await page.locator('#north').click();assert.equal((await state()).heading,0);await page.locator('#home').click();await settled();
for(const year of [1765,1900,2026]){await page.locator('#year').fill(String(year));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const result=await page.evaluate(()=>{const {manifest,slider}=__atlas;let checked=0,bad=0;for(const content of __visibleContents.values())for(let i=0;i<content.featuresLength;i++){const f=content.getFeature(i),y=f.getProperty('constructionYear');checked++;if(f.show!==(y==null||y<=slider.year))bad++;}return {checked,bad,hud:Number(document.querySelector('#visible-count').textContent.replaceAll(',','')),expected:manifest.filter(b=>b.constructionYear===null||b.constructionYear<=slider.year).length};});assert.equal(result.bad,0);assert.equal(result.hud,result.expected);assert.ok(result.checked>0);console.log('Year',year,result);}
// Picking still works with custom pan controls.
const hit=await page.evaluate(()=>{const scene=__atlas.viewer.scene;for(let y=340;y<690;y+=16)for(let x=420;x<1120;x+=16){const f=scene.pick({x,y});if(f?.getProperty?.('constructionYear'))return {x,y,year:f.getProperty('constructionYear')};}return null;});assert.ok(hit);await page.mouse.click(hit.x,hit.y);assert.equal(await page.locator('[data-metric=age] .metric-value').textContent(),String(hit.year));await page.locator('#close-building').click();
await page.locator('#year').fill('1900');await page.locator('#play').click();await page.waitForFunction(()=>__atlas.slider.year>1900);await page.locator('#play').click();await page.locator('#year').fill('2026');
const heading=(await state()).heading;await page.locator('#orbit').click();await page.waitForFunction(h=>__atlas.nav.state.heading!==h,heading);await page.locator('#orbit').click();
await page.locator('#labels-toggle').click();await page.waitForFunction(()=>document.querySelectorAll('.map-label:not([hidden])').length===0);await page.locator('#labels-toggle').click();
await page.locator('button[data-theme="day"]').click();await page.waitForFunction(()=>document.body.dataset.theme==='day');await page.screenshot({path:'artifacts/atlas-daylight.png'});await page.locator('button[data-theme="dusk"]').click();await page.waitForFunction(()=>document.body.dataset.theme==='dusk');
await page.locator('.district-button').filter({hasText:'Vallila'}).click();await settled();assert.equal(await page.locator('#area').textContent(),'Vallila');await page.waitForFunction(()=>__atlas.tileset.tilesLoaded);await page.screenshot({path:'artifacts/atlas-vallila.png'});
await page.locator('#map-search').fill('Katajanokka');await page.locator('#search-results button').first().click();await settled();assert.equal(await page.locator('#area').textContent(),'Katajanokka');await page.locator('#map-search').fill('Aleksanterinkatu');await page.locator('#search-results button').first().waitFor({state:'visible'});assert.ok(await page.locator('#search-results button').count()>0);await page.keyboard.press('Escape');
await page.locator('#home').click();await settled();await page.locator('#map-search').fill('');await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);await page.screenshot({path:'artifacts/atlas-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#zoom-in').click();// Test native touch events in a touch-enabled browser context.
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),touch=await mobile.newPage();await touch.goto('http://localhost:5173/?layer=age&year=2026');await touch.waitForFunction(()=>window.__atlas,null,{timeout:90000});
const cdp=await mobile.newCDPSession(touch),tstate=()=>touch.evaluate(()=>({...__atlas.nav.state}));const t0=await tstate();
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:210,y:500,id:0}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:280,y:510,id:0}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual((await tstate()).lon,t0.lon);
const r0=(await tstate()).range;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:195,y:490,id:0},{x:265,y:490,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:165,y:490,id:0},{x:300,y:490,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok((await tstate()).range<r0,'pinch out must zoom in');await mobile.close();
assert.deepEqual(errors,[]);console.log('PASS: navigation, streamed visibility, labels, themes, neighborhoods, search and mobile.');await browser.close();
