import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {normalizeRatu,parseYear,buildRegisterIndex,joinBuilding} from './lib.js';
import {triangulate} from './geometry.js';
import {visibleAt,initialYear} from '../viewer/src/YearSlider.js';
import {PUBLIC} from './config.js';
test('RATU normalization never equates missing identifiers',()=>{assert.equal(normalizeRatu(null),null);assert.equal(normalizeRatu(''),null);assert.equal(normalizeRatu(0),null);assert.equal(normalizeRatu('0046011.0'),'46011');assert.equal(normalizeRatu('BID_123'),null)});
test('Completion years reject placeholders and future values',()=>{assert.equal(parseYear('1936-12-31T00:00:00+02:00'),1936);for(const value of [null,'','0000-01-01','unknown','1880?','3025-01-01'])assert.equal(parseYear(value),null)});
test('ID join handles conflicts and never guesses an unmatched year',()=>{const index=buildRegisterIndex([{properties:{ratu:12,c_valmpvm:'1900-01-01'}},{properties:{ratu:'12',c_valmpvm:'1920-01-01'}},{properties:{ratu:14,c_valmpvm:'1880-01-01'}}]);assert.equal(joinBuilding('a',12,index).joinStatus,'conflicting-years');assert.equal(joinBuilding('a',12,index).constructionYear,null);assert.equal(joinBuilding('b',14,index).constructionYear,1880);assert.equal(joinBuilding('c',null,index).joinStatus,'unmatched')});
test('Triangulation preserves a courtyard hole',()=>{const ts=triangulate([[[0,0,0],[10,0,0],[10,10,0],[0,10,0]],[[3,3,0],[7,3,0],[7,7,0],[3,7,0]]]);const area=ts.reduce((s,[a,b,c])=>s+Math.abs((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))/2,0);assert.equal(area,84)});
test('Timeline boundary and deep links are consistent',()=>{assert.equal(visibleAt({constructionYear:1900},1899),false);assert.equal(visibleAt({constructionYear:1900},1900),true);assert.equal(visibleAt({constructionYear:null},1765),true);assert.equal(initialYear('?year=1000',1765,2026),1765);assert.equal(initialYear('?year=9999',1765,2026),2026);assert.equal(initialYear('?year=abc',1765,2026),1765)});
test('Generated spatial tiles match every manifest row',()=>{
 const m=JSON.parse(fs.readFileSync(`${PUBLIC}buildings-manifest.json`)),tiles=JSON.parse(fs.readFileSync(`${PUBLIC}tileset/tileset.json`));let total=0;
 for(const tile of tiles.root.children){const rows=m.filter(r=>r.tileContentUri===tile.content.uri),b=fs.readFileSync(`${PUBLIC}tileset/${tile.content.uri}`);assert.equal(b.toString('utf8',0,4),'b3dm');assert.equal(b.readUInt32LE(4),1);assert.equal(b.readUInt32LE(8),b.length);const ftl=b.readUInt32LE(12),btl=b.readUInt32LE(20),ft=JSON.parse(b.toString('utf8',28,28+ftl)),bt=JSON.parse(b.toString('utf8',28+ftl,28+ftl+btl));assert.equal(ft.BATCH_LENGTH,rows.length);for(const row of rows){assert.equal(bt.buildingId[row.tileFeatureId],row.buildingId);assert.equal(bt.constructionYear[row.tileFeatureId],row.constructionYear);assert.ok(row.position[0]>24&&row.position[0]<26&&row.position[1]>60&&row.position[1]<61);}const glbOffset=28+ftl+btl;assert.equal(glbOffset%8,0);assert.equal(b.toString('utf8',glbOffset,glbOffset+4),'glTF');total+=rows.length;}
 assert.equal(total,m.length);assert.equal(new Set(m.map(r=>r.buildingId)).size,m.length);const summary=JSON.parse(fs.readFileSync(`${PUBLIC}dataset.json`));assert.equal(summary.joined+summary.unknown,m.length);assert.ok(summary.joined>0);
});
test('Geographic context includes provenance, real labels and neighborhood coverage',()=>{const c=JSON.parse(fs.readFileSync(`${PUBLIC}map/context.json`));assert.ok(c.labels.length>100);assert.ok(c.labels.every(l=>Number.isFinite(l.position[0])&&Number.isFinite(l.position[1])&&l.name));assert.ok(c.neighborhoods.some(n=>n.name==='Kallio'&&n.count>0));assert.ok(c.neighborhoods.length>10);assert.ok(c.source.endpoint.startsWith('https://kartta.hel.fi/'));});
