import * as C from 'cesium';
import 'cesium/Build/Cesium/Widgets/widgets.css';
import './style.css';
import {YearSlider,visibleAt,initialYear} from './YearSlider';
import {MapNavigation} from './MapNavigation';
import {MapContext} from './MapContext';
const svg=(path)=>`<svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
const icons={home:svg('<path d="m3 11 9-8 9 8M5 10v11h14V10M9 21v-8h6v8"/>'),search:svg('<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>'),layers:svg('<path d="m3 8 9-5 9 5-9 5-9-5Zm0 5 9 5 9-5M3 18l9 5 9-5"/>'),sun:svg('<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>'),moon:svg('<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>')};
document.querySelector('#app').innerHTML=`
<div id="scene"></div><div class="vignette"></div><div id="map-labels" aria-hidden="true"></div>
<header><a class="brand" href="/" aria-label="Helsinki through time home"><span class="brand-mark">H<span>↗</span></span><span>HELSINKI<span class="brand-sub">THROUGH TIME</span></span></a>
<div class="search-wrap"><span>${icons.search}</span><label class="sr-only" for="map-search">Find a street, building or neighborhood</label><input id="map-search" placeholder="Find a street, building or neighborhood" autocomplete="off" aria-controls="search-results" aria-expanded="false"><kbd>/</kbd><div id="search-results" hidden></div></div>
<button id="about" class="text-button">About this atlas <span>↗</span></button></header>
<main class="intro"><div class="eyebrow"><span class="short-rule"></span> AN OPEN CITY ATLAS</div><h1>A city. Centuries<br>in the making.</h1><p>Explore Helsinki’s surviving architecture,<br>one year and one neighborhood at a time.</p></main>
<aside class="explore-panel"><div class="panel-heading"><span class="eyebrow">EXPLORE NEIGHBORHOODS</span><span id="district-count" class="small-pill">—</span></div><div id="districts" class="districts"></div><p class="coverage-note">Partial 3D coverage · 2019 city model</p><div class="panel-divider"></div><div class="layer-heading"><span>${icons.layers} Map appearance</span><button id="labels-toggle" aria-pressed="true">Labels <span>ON</span></button></div><div class="theme-switch"><button data-theme="dusk" aria-pressed="true">${icons.moon} Dusk</button><button data-theme="day" aria-pressed="false">${icons.sun} Daylight</button></div><div class="location"><span class="location-dot">⌖</span><span id="area">Kruununhaka</span></div></aside>
<aside class="era-card"><div class="eyebrow">HELSINKI IN</div><div class="era-year" id="era-year">—</div><div id="era-name">Loading timeline</div><div class="era-divider"></div><div class="metric"><strong id="visible-count">—</strong><span>buildings revealed</span></div><div class="coverage"><span id="coverage-bar"></span></div><small id="count-detail">Loading verified city data…</small></aside>
<nav class="map-tools" aria-label="Map controls"><button id="home" title="Reset camera" aria-label="Reset camera">${icons.home}</button><span></span><button id="zoom-in" title="Zoom in (+)" aria-label="Zoom in">+</button><button id="zoom-out" title="Zoom out (−)" aria-label="Zoom out">−</button><span></span><button id="perspective" aria-label="Toggle top-down view" title="Switch 2D / 3D view">2D</button><button id="rotate-left" aria-label="Rotate left" title="Rotate left">↶</button><button id="rotate-right" aria-label="Rotate right" title="Rotate right">↷</button><button id="orbit" aria-label="Automatic camera orbit" title="Automatic orbit" aria-pressed="false">↻</button></nav>
<div class="north"><button id="north" aria-label="Face north" title="Face north"><span>N</span><svg id="compass-arrow" width="24" height="34" viewBox="0 0 24 38" aria-hidden="true"><path d="M12 0 21 30 12 23Z" fill="#e2c4a0"/><path d="M12 0 3 30 12 23Z" fill="#687e83"/></svg></button></div>
<div class="map-caption"><span class="scale-line"></span><span id="map-scale">200 m</span><span class="map-instructions">Drag to explore <i>·</i> Scroll to zoom <i>·</i> Shift + drag to rotate</span></div>
<section class="timeline" aria-label="Construction year timeline"><div class="timeline-top"><div><span class="eyebrow">WATCH THE CITY GROW</span><span class="timeline-hint">Drag the timeline to reveal its history</span></div><div class="legend"><span><i class="warm"></i>Built by <b id="legend-year">—</b></span><span><i class="gray"></i>Year unknown</span></div></div>
<div class="timeline-main"><button id="play" class="play" aria-label="Play timeline" aria-pressed="false" disabled>▶</button><div class="year-current"><strong id="year-current">—</strong><span>SELECTED YEAR</span></div><div class="scrubber"><div id="histogram" class="histogram" aria-hidden="true"></div><label class="sr-only" for="year">Construction year</label><input id="year" type="range" min="1765" max="2026" value="2026" disabled><div id="ticks" class="ticks"></div></div><label class="speed"><span>PLAYBACK</span><select id="speed" aria-label="Playback speed"><option value="5">5 yr / sec</option><option value="12" selected>12 yr / sec</option><option value="30">30 yr / sec</option></select></label></div>
<div class="timeline-bottom"><span><span class="tiny-dot"></span> REAL BUILDINGS. REAL CONSTRUCTION YEARS.</span><button class="text-button" id="share">Share this year <span>↗</span></button></div></section>
<footer><span>2019 building snapshot · Present-day reference map · Not a historical reconstruction</span><button id="sources" class="text-button">© City of Helsinki · CC BY 4.0 <span>↗</span></button></footer>
<div id="loading" class="loading"><div class="loader"></div><strong>Finding our place in Helsinki</strong><span>Loading the city model and its geography</span></div>
<aside id="building-card" class="building-card" hidden><button id="close-building" class="close" aria-label="Close building details">×</button><div class="eyebrow">BUILDING RECORD</div><h2 id="building-address"></h2><div id="building-year"></div><dl><dt>Building type</dt><dd id="building-purpose"></dd><dt>Register ID · RATU</dt><dd id="building-ratu"></dd><dt>Geometry detail</dt><dd id="building-lod"></dd></dl><p id="building-status"></p></aside>
<dialog id="about-dialog"><button class="close" id="close-about" aria-label="Close about dialog">×</button><div class="eyebrow">ABOUT THE ATLAS</div><h2>A city is never<br>built in a day.</h2><p>Explore real Helsinki CityGML buildings, joined to official register completion dates by RATU. No buildings or dates are invented.</p><div class="dialog-stats" id="data-stats"></div><h3>More Helsinki, honestly represented</h3><p>The <strong>26 March 2019</strong> geometry snapshot covers parts of central and eastern Helsinki. Neighborhood shortcuts list the buildings available in each area, not their complete building inventory. Planned objects are excluded; buildings demolished since 2019 may remain.</p><p>Land, water, parks, streets and names come from Helsinki’s <strong>present-day reference map</strong>. These layers stay fixed as the building timeline changes. Modern building footprints are omitted from the basemap to keep the year reveal clear.</p><p>This is <strong>not a reconstruction of historical Helsinki</strong>. Buildings demolished before the geometry snapshot are absent. Unknown completion years always remain visible in gray. Source N2000 heights are retained without geoid correction or a surveyed terrain model.</p><h3>Explore with mouse, touch or keyboard</h3><p>Drag to pan. Scroll or pinch to zoom. Shift-drag or right-drag to rotate and tilt. Focus the map and use arrow keys to pan, + / − to zoom, or Home to reset. Press Space to play the timeline. Use the search to find a building, street or neighborhood.</p><h3>Sources</h3><ul><li><a href="https://3d.hel.ninja/data/citygml/" target="_blank" rel="noopener">Helsinki 3D City Model ↗</a></li><li><a href="https://hri.fi/data/fi/dataset/helsingin-rakennukset" target="_blank" rel="noopener">Helsinki building register ↗</a></li><li><a href="/dataset.json" target="_blank" rel="noopener">Geometry and join provenance ↗</a></li><li><a href="/map/context.json" target="_blank" rel="noopener">Map labels and geographic provenance ↗</a></li></ul><p class="fine-print">City of Helsinki · CC BY 4.0. Source textures are replaced with warm architectural materials.</p></dialog><div id="toast" role="status"></div>`;
const $=s=>document.querySelector(s);
let viewer,tileset,manifest,slider,summary,nav,mapContext,selected;
const loadedContents=new Map();const now=new Date().getFullYear();
const era=year=>year<1800?'The earliest surviving layers':year<1850?'An emerging capital':year<1900?'A city taking shape':year<1940?'A new urban century':year<1970?'The post-war city':year<2000?'A modern capital':'The contemporary city';
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function closeSelection(){if(selected){try{selected.color=C.Color.WHITE;}catch{/* A streamed tile may have been evicted. */}selected=undefined;tileset?.makeStyleDirty();}$('#building-card').hidden=true;}
function styleBuildings(){if(!tileset||!slider)return;const day=mapContext?.theme==='day';tileset.style=new C.Cesium3DTileStyle({show:`\${constructionYear} === undefined || \${constructionYear} === null || \${constructionYear} <= ${slider.year}`,color:{conditions:[['${constructionYear} === null || ${constructionYear} === undefined',`color('${day?'#829d9e':'#68848c'}')`],['${constructionYear} < 1900',`color('${day?'#e7d8bd':'#ebcca3'}')`],['${constructionYear} < 1940',`color('${day?'#d2b895':'#dabb91'}')`],['true',`color('${day?'#bc9879':'#bc9477'}')`]]}});}
function update(year){closeSelection();const visible=manifest.filter(b=>visibleAt(b,year)).length;for(const id of ['era-year','year-current','legend-year'])$(`#${id}`).textContent=year;$('#era-name').textContent=era(year);$('#visible-count').textContent=visible.toLocaleString();$('#count-detail').textContent=`of ${manifest.length.toLocaleString()} in the model · ${summary.unknown} unknown years`;
 $('#coverage-bar').style.width=`${visible/manifest.length*100}%`;$('#year').style.setProperty('--progress',`${(year-slider.min)/(slider.max-slider.min)*100}%`);document.querySelectorAll('.histogram i').forEach(bar=>bar.classList.toggle('active',Number(bar.dataset.year)<=year));styleBuildings();const url=new URL(location.href);url.searchParams.set('year',year);history.replaceState(null,'',url);
}
function showBuilding(feature){closeSelection();selected=feature;feature.color=C.Color.fromCssColorString('#f8efc7');$('#building-card').hidden=false;$('#building-address').textContent=feature.getProperty('address')||'An unnamed building';const year=feature.getProperty('constructionYear');$('#building-year').textContent=year??'Year unknown';$('#building-purpose').textContent=feature.getProperty('purpose')||'Not recorded';$('#building-ratu').textContent=feature.getProperty('ratu')||'Not matched';$('#building-lod').textContent=`LOD${feature.getProperty('lod')} · CityGML`;$('#building-status').textContent=year==null?'No reliable completion year was found. This building stays visible throughout the timeline.':'Completion date from Helsinki’s building register. Geometry from the 2019 city model.';}
function nearestArea(lon,lat){const areas=mapContext?.data.neighborhoods||[];return areas.reduce((best,n)=>{const distance=Math.hypot((n.position[0]-lon)*.5,n.position[1]-lat);return !best||distance<best.distance?{...n,distance}:best;},null);}
function navigate(position,range=1800){closeSelection();nav.flyTo(position,range);}
function buildSearch(context){
 const list=[...context.neighborhoods.map(n=>({name:n.name,detail:`Neighborhood · ${n.count} modeled buildings`,position:n.position,range:2200})),...manifest.filter(b=>b.address).map(b=>({name:b.address,detail:`Building · ${b.constructionYear??'year unknown'}`,position:b.position,range:600,year:b.constructionYear}))];
 const names=new Set(context.neighborhoods.map(n=>n.name));for(const l of context.labels.filter(l=>['street','district','place'].includes(l.type))){if(names.has(l.name))continue;names.add(l.name);list.push({name:l.name,detail:`${l.type==='street'?'Street':'Place'} · reference map`,position:l.position,range:1100});}
 const input=$('#map-search'),results=$('#search-results');
 const hide=()=>{results.hidden=true;input.setAttribute('aria-expanded','false');};
 input.addEventListener('input',()=>{results.replaceChildren();const query=input.value.trim().toLocaleLowerCase('fi');if(query.length<2){hide();return;}const matches=list.filter(r=>r.name.toLocaleLowerCase('fi').includes(query)).sort((a,b)=>Number(b.name.toLowerCase().startsWith(query))-Number(a.name.toLowerCase().startsWith(query))).slice(0,8);
  results.hidden=false;input.setAttribute('aria-expanded','true');if(!matches.length){const p=document.createElement('p');p.textContent='No matching place in this map. Try a street or neighborhood.';results.append(p);}
  for(const item of matches){const button=document.createElement('button'),name=document.createElement('strong'),detail=document.createElement('span');name.textContent=item.name;detail.textContent=item.detail;button.append(name,detail);button.onclick=()=>{if(item.year&&slider.year<item.year){slider.pause();slider.set(item.year);toast(`Moved to ${item.year} to reveal this building.`);}navigate(item.position,item.range);input.value=item.name;hide();};results.append(button);}
 });
 input.addEventListener('keydown',e=>{if(e.key==='Escape')hide();if(e.key==='ArrowDown'){e.preventDefault();results.querySelector('button')?.focus();}if(e.key==='Enter')results.querySelector('button')?.click();});
 results.addEventListener('keydown',e=>{const items=[...results.querySelectorAll('button')],i=items.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();items[(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}if(e.key==='Escape'){hide();input.focus();}});
 document.addEventListener('pointerdown',e=>{if(!e.target.closest('.search-wrap'))hide();});
}
async function init(){
 const get=async url=>{const r=await fetch(url);if(!r.ok)throw Error(`Could not load ${url} (${r.status})`);return r.json();};
 let context;[manifest,summary,context]=await Promise.all([get('/buildings-manifest.json'),get('/dataset.json'),get('/map/context.json')]);
 viewer=new C.Viewer('scene',{baseLayer:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,navigationHelpButton:false,animation:false,timeline:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,skyBox:false,skyAtmosphere:false,scene3DOnly:true,requestRenderMode:false,contextOptions:{webgl:{alpha:false}}});
 viewer.scene.backgroundColor=C.Color.fromCssColorString('#102c38');viewer.scene.globe.baseColor=C.Color.fromCssColorString('#102e3c');viewer.scene.globe.showGroundAtmosphere=false;viewer.scene.globe.enableLighting=false;viewer.scene.globe.depthTestAgainstTerrain=false;viewer.scene.fog.enabled=false;
 if(viewer.scene.sun)viewer.scene.sun.show=false;if(viewer.scene.moon)viewer.scene.moon.show=false;
 const frame=C.Transforms.eastNorthUpToFixedFrame(C.Cartesian3.fromDegrees(...summary.center));const direction=C.Matrix4.multiplyByPointAsVector(frame,new C.Cartesian3(.5,.3,-.8),new C.Cartesian3());
 viewer.scene.light=new C.DirectionalLight({direction:C.Cartesian3.normalize(direction,direction),intensity:2.3});viewer.scene.postProcessStages.fxaa.enabled=true;viewer.resolutionScale=Math.min(devicePixelRatio,1.5);
 mapContext=new MapContext(viewer,context);
 nav=new MapNavigation(viewer,state=>{const area=nearestArea(state.lon,state.lat);$('#area').textContent=area&&area.distance<.012?area.name:'Helsinki · reference map';$('#orbit').setAttribute('aria-pressed',String(nav?.orbit||false));$('#compass-arrow').style.transform=`rotate(${-state.heading}deg)`;$('#perspective').textContent=state.pitch<-75?'3D':'2D';if(nav){const m=nav.metersPerPixel()*70;$('#map-scale').textContent=m>=1000?`${(m/1000).toFixed(1)} km`:`${Math.round(m/10)*10} m`;}});
 tileset=await C.Cesium3DTileset.fromUrl('/tileset/tileset.json',{maximumScreenSpaceError:8,cacheBytes:128*1024*1024});viewer.scene.primitives.add(tileset);
 tileset.tileVisible.addEventListener(tile=>{if(tile.content?.featuresLength)loadedContents.set(tile.content.url,tile.content);});tileset.tileUnload.addEventListener(tile=>loadedContents.delete(tile.content.url));tileset.tileFailed.addEventListener(error=>toast(`A city tile could not load. ${error.message}`));
 const min=summary.minYear,max=now,binCount=80,counts=Array(binCount).fill(0);manifest.forEach(b=>{if(b.constructionYear!==null)counts[Math.min(binCount-1,Math.floor((b.constructionYear-min)/(max-min)*binCount))]++;});const peak=Math.max(...counts);
 $('#histogram').innerHTML=counts.map((n,i)=>`<i data-year="${min+(i+1)*(max-min)/binCount}" style="height:${n?Math.max(6,n/peak*100):2}%"></i>`).join('');$('#ticks').innerHTML=[min,...[1800,1850,1900,1950,2000].filter(y=>y>min+10&&y<max-12),max].map(y=>`<span style="left:${(y-min)/(max-min)*100}%">${y}</span>`).join('');
 slider=new YearSlider({input:$('#year'),play:$('#play'),speed:$('#speed'),min,max,onChange:update});slider.set(initialYear(location.search,min,max));$('#play').disabled=false;$('#year').disabled=false;$('#data-stats').textContent=`${manifest.length.toLocaleString()} buildings · ${summary.joined.toLocaleString()} known years · ${context.neighborhoods.length} neighborhoods`;
 const order=['Kruununhaka','Katajanokka','Kallio','Sörnäinen','Hermanni','Vallila'];context.neighborhoods.sort((a,b)=>(order.indexOf(a.name)<0?100:order.indexOf(a.name))-(order.indexOf(b.name)<0?100:order.indexOf(b.name))||b.count-a.count);
 $('#district-count').textContent=context.neighborhoods.length;
 for(const n of context.neighborhoods){const button=document.createElement('button');button.className='district-button';const name=document.createElement('span'),count=document.createElement('small');name.textContent=n.name;count.textContent=n.count;button.append(name,count);button.title=`Explore ${n.name}: ${n.count} modeled buildings, partial coverage`;button.onclick=()=>{document.querySelectorAll('.district-button').forEach(b=>b.classList.remove('active'));button.classList.add('active');navigate(n.position,1900);};$('#districts').append(button);}
 buildSearch(context);
 const handler=new C.ScreenSpaceEventHandler(viewer.scene.canvas);handler.setInputAction(e=>{if(nav.dragged)return;const feature=viewer.scene.pick(e.position);if(feature instanceof C.Cesium3DTileFeature)showBuilding(feature);else closeSelection();},C.ScreenSpaceEventType.LEFT_CLICK);
 await Promise.all([mapContext.ready,new Promise((resolve,reject)=>{let stop;const timeout=setTimeout(()=>{stop?.();reject(Error('City tiles did not finish loading. Please reload.'));},60000);stop=viewer.scene.postRender.addEventListener(()=>{if(loadedContents.size&&tileset.tilesLoaded){stop();clearTimeout(timeout);resolve();}});})]);
 $('#loading').remove();window.__atlas={viewer,tileset,manifest,slider,nav,mapContext,loadedContents};
}
$('#home').onclick=()=>nav?.reset();$('#zoom-in').onclick=()=>nav?.zoom(.78);$('#zoom-out').onclick=()=>nav?.zoom(1.28);$('#rotate-left').onclick=()=>nav?.rotate(-25);$('#rotate-right').onclick=()=>nav?.rotate(25);$('#north').onclick=()=>nav&&nav.rotate(-nav.state.heading);$('#perspective').onclick=()=>nav?.togglePerspective();$('#orbit').onclick=()=>{if(nav){nav.orbit=!nav.orbit;nav.apply();}};
$('#labels-toggle').onclick=()=>{if(mapContext){mapContext.enabled=!mapContext.enabled;$('#labels-toggle').setAttribute('aria-pressed',String(mapContext.enabled));$('#labels-toggle span').textContent=mapContext.enabled?'ON':'OFF';mapContext.layout();}};
for(const button of document.querySelectorAll('.theme-switch button'))button.onclick=async()=>{if(!mapContext)return;try{await mapContext.setTheme(button.dataset.theme);document.querySelectorAll('.theme-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));styleBuildings();}catch(error){toast(`Map appearance could not load: ${error.message}`);}};
$('#close-building').onclick=closeSelection;for(const id of ['about','sources'])$(`#${id}`).onclick=()=>$('#about-dialog').showModal();$('#close-about').onclick=()=>$('#about-dialog').close();$('#about-dialog').addEventListener('click',e=>{if(e.target===$('#about-dialog'))$('#about-dialog').close();});
$('#share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast('Link copied — this year is ready to share.');}catch{toast('Copy the URL in your address bar to share this year.');}};
document.addEventListener('keydown',e=>{const editing=['INPUT','SELECT','BUTTON','A'].includes(document.activeElement.tagName);if(e.key==='/'&&!editing){e.preventDefault();$('#map-search').focus();}if(e.code==='Space'&&!editing&&!$('#about-dialog').open&&slider){e.preventDefault();slider.playing?slider.pause():slider.start();}if(e.code==='Escape')closeSelection();});
init().catch(error=>{console.error(error);const loading=$('#loading');if(!loading)return;loading.replaceChildren();const title=document.createElement('strong'),message=document.createElement('span'),retry=document.createElement('button');title.textContent='The city couldn’t load';message.textContent=error.message;retry.className='text-button';retry.textContent='Try again ↻';retry.onclick=()=>location.reload();loading.append(title,message,retry);});
